### ISSUE TITLE
embed code

### ISSUE THREAD

**Issue by josheewa** [jcgter777/School#5]
`function() {
    function prepareFrame() {
        var scrHeight = x + "px";
        alert(scrHeight);
        var ifrm = document.createElement("iframe");
        ifrm.setAttribute("src", web), ifrm.style.width = "100%", ifrm.style.height = scrHeight, document.body.insertBefore(ifrm, document.body.childNodes[0])
    }
    var web, x;
    x = screen.height, web = prompt("Website"), prepareFrame(), document.onkeydown = function(e) {
        if (e = e || window.event, 27 == e.keyCode) {
            var t = document.querySelector("iframe");
            t.parentNode.removeChild(t)
        }
    }
}();`

**Comment by CerebralDatabank** [comment]
This and [the other one](https://github.com/jcgter777/School/issues/6) aren't issues...
