### ISSUE TITLE
Discord embed code

### ISSUE THREAD

**Issue by josheewa** [jcgter777/School#6]
`<iframe src="https://titanembeds.com/embed/487373227761598465" height="600" width="800" frameborder="0"></iframe>`

**Comment by CerebralDatabank** [comment]
This and [the other one](https://github.com/jcgter777/School/issues/5) aren't issues... am closing.

**Comment by CerebralDatabank** [comment]
This and [the other one](https://github.com/jcgter777/School/issues/5) aren't issues...
